replicaCount: 1

image:
  repository: nourhenhachem/innodeploy-app
  tag: v1779144982
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx

  hosts:
    - host: dev.local
      paths:
        - path: /
          pathType: Prefix
