apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring

stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: discord
      group_by: ['alertname', 'namespace', 'app']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 2h

    receivers:
      - name: discord
        discord_configs:
          - webhook_url: "YOUR_DISCORD_WEBHOOK"
            send_resolved: true
            title: '{{ if eq .Status "resolved" }}✅ RESOLVED{{ else }}🚨 FIRING{{ end }}'
            message: |
              {{ range .Alerts }}
              Alert: {{ .Labels.alertname }}
              App: {{ .Labels.app }}
              Namespace: {{ .Labels.namespace }}
              Severity: {{ .Labels.severity }}
              Status: {{ .Status }}
              {{ end }}

      - name: email
        email_configs:
          - to: "YOUR_EMAIL"
            send_resolved: true
            headers:
              subject: '{{ if eq .Status "resolved" }}RESOLVED{{ else }}FIRING{{ end }}: InnoDeploy Alert'