
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-deploy2-dev
spec:
  source:
    repoURL: https://github.com/hachemn/innodeploy-gitops.git
    path: helm/innodeploy-chart
  destination:
    namespace: dev
