replicaCount: 1
image:
  repository: nourhenhachem/test-deploy2-dev
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
container:
  port: 3000
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: test-deploy2-dev.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: test-deploy2-dev-tls
      hosts:
        - test-deploy2-dev.192.168.49.2.nip.io
