---
- name: Setup InnoDeploy on EKS
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Connect kubectl to EKS
      shell: aws eks update-kubeconfig --name innodeploy-cluster --region us-east-1

    - name: Create namespaces
      shell: kubectl create namespace {{ item }} --dry-run=client -o yaml | kubectl apply -f -
      loop:
        - argocd
        - monitoring
        - dev
        - helm-dev

    - name: Install ArgoCD
      shell: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      ignore_errors: yes

    - name: Add Prometheus helm repo
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update

    - name: Install Prometheus + Grafana
      shell: |
        helm upgrade --install kube-prometheus-stack \
          prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace

    - name: Wait for ArgoCD
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s

    - name: Create innodeploy ArgoCD app
      shell: |
        kubectl apply -f - <<YAML
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: innodeploy-app
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: https://github.com/hachemn/innodeploy-gitops
            targetRevision: main
            path: helm/innodeploy-chart
            helm:
              valueFiles:
                - values-dev.yaml
            helm:
              valueFiles:
                - values-dev.yaml
          destination:
            server: https://kubernetes.default.svc
            namespace: dev
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
        YAML

    - name: Get ArgoCD password
      shell: kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode
      register: argocd_password

    - name: Show ArgoCD password
      debug:
        msg: "ArgoCD password: {{ argocd_password.stdout }}"

    - name: Wait for Grafana
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=grafana -n monitoring --timeout=300s

    - name: Get Grafana password
      shell: kubectl get secret kube-prometheus-stack-grafana -n monitoring -o jsonpath="{.data.admin-password}" | base64 --decode
      register: grafana_password

    - name: Show Grafana password
      debug:
        msg: "Grafana password: {{ grafana_password.stdout }}"

    - name: Apply ServiceMonitor
      shell: kubectl apply -f ~/innodeploy/innodeploy-gitops/base/servicemonitor.yaml

    - name: Fix Grafana datasource
      shell: |
        PROM_IP=$(kubectl get svc kube-prometheus-stack-prometheus -n monitoring -o jsonpath='{.spec.clusterIP}')
        kubectl patch configmap kube-prometheus-stack-grafana-datasource -n monitoring --type='json' \
          -p="[{\"op\": \"replace\", \"path\": \"/data/datasource.yaml\", \"value\": \"apiVersion: 1\ndatasources:\n- name: Prometheus\n  type: prometheus\n  url: http://${PROM_IP}:9090\n  access: proxy\n  isDefault: true\n\"}]"
        kubectl rollout restart deployment/kube-prometheus-stack-grafana -n monitoring

    - name: Apply Alertmanager config
      shell: |
        kubectl delete secret alertmanager-kube-prometheus-stack-alertmanager -n monitoring --ignore-not-found
        cat ~/innodeploy/innodeploy-gitops/alertmanager-config.yaml | \
          sed 's/alertmanager-monitoring-kube-prometheus-alertmanager/alertmanager-kube-prometheus-stack-alertmanager/' | \
          kubectl apply -f -
        kubectl rollout restart statefulset/alertmanager-kube-prometheus-stack-alertmanager -n monitoring

    - name: Apply PrometheusRule
      shell: kubectl apply -f ~/innodeploy/innodeploy-gitops/base/prometheusrule.yaml
