global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'hachemnourhen8@gmail.com'
  smtp_auth_username: 'hachemnourhen8@gmail.com'
  smtp_auth_password: 'rpvh zoyx gwpw mfiw'
  smtp_require_tls: true

route:
  receiver: discord-email
  group_by: ['alertname', 'namespace']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:

  - name: discord-email

    discord_configs:
      - webhook_url: "https://discord.com/api/webhooks/1502017723067138148/ufZtiSP0tLnLvD1zkCno2T1sUH_3K4hejnAkRuR1v7leDZEJ9gPnGsSfTvHLXvbAObtd"
        send_resolved: true
        title: '{{ if eq .Status "resolved" }}✅ RESOLVED{{ else }}🚨 ALERT FIRED{{ end }}'
        message: |
          {{ range .Alerts }}
          Alert: {{ .Labels.alertname }}
          Namespace: {{ .Labels.namespace }}
          Severity: {{ .Labels.severity }}
          Status: {{ .Status }}
          Description: {{ .Annotations.description }}
          {{ end }}

    email_configs:
      - to: 'hachemnourhen8@gmail.com'
        send_resolved: true
        headers:
          subject: '{{ if eq .Status "resolved" }}✅ RESOLVED{{ else }}🚨 FIRED{{ end }}: InnoDeploy Alert'
        html: |
          <h2>{{ .Status | toUpper }}</h2>
          {{ range .Alerts }}
          <p><b>Alert:</b> {{ .Labels.alertname }}</p>
          <p><b>Namespace:</b> {{ .Labels.namespace }}</p>
          <p><b>Severity:</b> {{ .Labels.severity }}</p>
          <p><b>Description:</b> {{ .Annotations.description }}</p>
          <hr>
          {{ end }}
