apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: innodeploy-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: innodeploy.rules

      rules:
        - alert: InnodeployAppDown

          expr: absent(up{service="innodeploy-app-dev", namespace="dev"})

          for: 1m

          labels:
            severity: critical

          annotations:
            summary: "Innodeploy app is DOWN"
            description: "Prometheus cannot reach the app for 1 minute"