apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: innodeploy-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack

spec:
  groups:
    - name: innodeploy.rules
      rules:

        - alert: InnodeployAppDown
          expr: up{namespace="dev", service="innodeploy-app-innodeploy-chart"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "InnoDeploy app is DOWN"
            description: "App is not responding"

        - alert: InnodeployNoReadyReplicas
          expr: kube_deployment_status_replicas_available{namespace="dev"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "No ready replicas"
            description: "Deployment has 0 available pods"

        - alert: InnodeployPodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="dev", pod=~"innodeploy-app-.*"}[10m]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Crash looping pod"
            description: "Pod restarting too often"

        - alert: InnodeployHighMemory
          expr: sum(container_memory_working_set_bytes{namespace="dev", pod=~"innodeploy-app-.*", container!=""}) > 200000000
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage"
            description: "Memory > 200MB"
