apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: innodeploy-app
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app.kubernetes.io/name: innodeploy-chart
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
