apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: innodeploy-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: innodeploy-chart
      app.kubernetes.io/instance: helm-dev
  namespaceSelector:
    matchNames:
      - helm-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s